name: exponential action

on:
  push:
    tags: [ '*.[0-9]' ]


jobs:
  update-and-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    - name: add n tags
      run: |
        ./exponential/check_counter_and_tag.sh 2