name: recursive action

on:
  push:
    branches: [ recursive ]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

    - name: update counter and commit
      run: |
        ./recursive/check_counter_and_commit.sh