name: recursive action

on:
  push:
    branches: [ recursive ]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: update counter and commit
      env:
        PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      run: |
        ./recursive/check_counter_and_commit.sh