name: smart light action

on:
  push:
    branches: [ smart-lights ]

jobs:
  smart_lights_job:
    runs-on: ubuntu-latest
    name: Turn on smart lights
    steps:
    - uses: actions/checkout@v2

    - name: Trigger lights 
      uses: ./smart-lights
      with:
        VESYNC_PASS: ${{ secrets.VESYNC_PASS }}
